# Generated by Django 6.0.3 on 2026-03-24 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cotisations", "0001_initial"),
        ("membres", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Benefice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_versement", models.DateTimeField(blank=True, null=True)),
                ("verse", models.BooleanField(default=False)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefices",
                        to="cotisations.cycle",
                    ),
                ),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefices",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Benefice",
                "verbose_name_plural": "Benefices",
                "ordering": ["-date_versement"],
            },
        ),
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("paye", "Payé"),
                            ("en_retard", "En retard"),
                            ("annule", "Annulé"),
                        ],
                        default="en_attente",
                        max_length=15,
                    ),
                ),
                (
                    "moyen_paiement",
                    models.CharField(
                        choices=[
                            ("especes", "Espèces"),
                            ("mobile_money", "Mobile Money"),
                            ("virement", "Virement"),
                            ("cheque", "Chèque"),
                        ],
                        default="especes",
                        max_length=15,
                    ),
                ),
                ("date_echeance", models.DateField()),
                ("date_paiement", models.DateTimeField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=50, unique=True)),
                ("commentaire", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements",
                        to="cotisations.cycle",
                    ),
                ),
                (
                    "groupe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements",
                        to="membres.groupe",
                    ),
                ),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "ordering": ["-date_echeance"],
            },
        ),
    ]
