# Generated by Django 6.0.3 on 2026-03-24 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Groupe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "montant_cotisation",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "frequence",
                    models.CharField(
                        choices=[
                            ("hebdomadaire", "Hebdomadaire"),
                            ("mensuel", "Mensuel"),
                            ("trimestriel", "Trimestriel"),
                        ],
                        default="mensuel",
                        max_length=20,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("termine", "Terminé"),
                            ("suspendu", "Suspendu"),
                        ],
                        default="actif",
                        max_length=10,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_debut", models.DateField()),
                (
                    "createur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groupes_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Groupe",
                "verbose_name_plural": "Groupes",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Membre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telephone", models.CharField(max_length=20)),
                ("adresse", models.TextField(blank=True)),
                ("profession", models.CharField(blank=True, max_length=100)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("inactif", "Inactif"),
                            ("suspendu", "Suspendu"),
                        ],
                        default="actif",
                        max_length=10,
                    ),
                ),
                ("date_inscription", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membre",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Membre",
                "verbose_name_plural": "Membres",
                "ordering": ["user__last_name"],
            },
        ),
        migrations.CreateModel(
            name="Adhesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_adhesion", models.DateTimeField(auto_now_add=True)),
                ("ordre_benefice", models.IntegerField(default=0)),
                ("actif", models.BooleanField(default=True)),
                (
                    "groupe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adhesions",
                        to="membres.groupe",
                    ),
                ),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adhesions",
                        to="membres.membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adhesion",
                "verbose_name_plural": "Adhesions",
                "ordering": ["ordre_benefice"],
                "unique_together": {("membre", "groupe")},
            },
        ),
    ]
