# Generated by Django 6.0.3 on 2026-03-24 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("membres", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField()),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                (
                    "montant_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("termine", models.BooleanField(default=False)),
                (
                    "beneficiaire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cycles_beneficiaire",
                        to="membres.membre",
                    ),
                ),
                (
                    "groupe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cycles",
                        to="membres.groupe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cycle",
                "verbose_name_plural": "Cycles",
                "ordering": ["numero"],
                "unique_together": {("groupe", "numero")},
            },
        ),
    ]
